services:
  db:
    build: .
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5454:5432
    volumes:
      # - ./data:/var/lib/postgresql/data
      - pg_data:/var/lib/postgresql/data
      - ./queries:/tmp/queries
      - ./shapefiles:/tmp/shapefiles

volumes:
  pg_data: